### PR TITLE
This must fix the test.

### PR DESCRIPTION
**Pull request by hemanth**
engine and travis version

### CODE REVIEW

**Comment by mklabs** [comment]
Thx again @hemanth

**Comment by hemanth** [comment]
NP @mklabs, thank you!

**Comment by mklabs** [comment]
Plan to use 140-opts ? :d 

I first wrote it a long time ago, I don't remember why. 5bfd955a6410b125683dc629636ab74217677b6f

That was the first and only commit until yesterday. I never really used but its kinda useful as a drop in. I'm using it for https://github.com/vimlab/t.vim

**Comment by hemanth** [comment]
Must of my stuff are on [meow](http://npm.im/meow) as of now, but would love to cover this in [nmotw](https://nmotw.in) 👼

**Comment by mklabs** [comment]
wow https://nmotw.in/ looks cool, bookmarked.

**Comment by mklabs** [comment]
btw, speaking of meow, sindresorhus/meow#38 made me start https://github.com/mklabs/roar (name courtesy of Sindre)

It works with meow. this is basically my CLI toolkit, I like es6 classes :p

**Comment by hemanth** [comment]
Feel free to subscribe -> https://nmotw.in/subscribe ;)

Roar heh heh epic!

**Comment by mklabs** [comment]
Subscribed, don't spam me!

**Pull request merged**
